apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-eta-deploy
  labels:
    app: bankapp-eta-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-eta-app
  template:
    metadata:
      labels:
        app: bankapp-eta-app
    spec:
      containers:
      - name: bankapp-eta-container
<<<<<<< HEAD
        image: sheelashrinivas/bankapp-eta-app
=======
        image: loksaieta/bankapp-eta-app
>>>>>>> 12ff9b793978b55d9a7d871ad62322fd6eb6218a
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-eta-np-service
  labels:
    app: bankapp-eta-app
spec:
  selector:
    app: bankapp-eta-app

  type: NodePort
  ports:
<<<<<<< HEAD
  - nodePort: 31033   
=======
  - nodePort: 31033    
>>>>>>> 12ff9b793978b55d9a7d871ad62322fd6eb6218a
    port: 8082
    targetPort: 8082
